### ISSUE TITLE
Linter errors on install

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Upstream-BugFixes#1]
When I install this style, I get a load of linter errors in Stylus, is that expected?

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/115237/88698487-66078800-d106-11ea-904f-6d1e98b1ac85.png">

**Comment by silverwind** [comment]
Probably related to Stylus unable to lint stylus?

<img width="238" alt="image" src="https://user-images.githubusercontent.com/115237/88698617-92230900-d106-11ea-9cdb-390afdeb8222.png">

**Comment by silverwind** [comment]
Disabled linter in Stylus. I don't need it anyways as I prefer external editor :)

**Comment by the-j0k3r** [comment]
Stylus linters dont support stylus lang preprocessor (not the only one iirc) theres a issue upstream at stylus about it even asking to disable linters for some preprocessors or add stylus linter, but nothing has happened with that.

See https://github.com/openstyles/stylus/issues/880

so yes its expected and very safe to ignore =)
