### ISSUE TITLE
Avatar and text should be on the same line

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Upstream-BugFixes#2]
* **Browser**: Firefox
* **Operating System**: macOS
* **Link to page with the issue**: https://github.com/go-gitea/gitea/pull/12448/commits/02c870b9758efda96777bd59f45e16a5fb01268c
* **Screenshot**:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/115237/90314860-279c0680-df17-11ea-934a-cd29dedd0963.png">

**Comment by the-j0k3r** [comment]
It seems it is, is there some special conditions in which the bug is visible?

This is what I see.

![Capture](https://user-images.githubusercontent.com/31389848/90321001-36e67880-df46-11ea-9dcd-0e155a629607.PNG)

Firefox Windows

Is this by chance your font usercss style interfering?

**Comment by silverwind** [comment]
Seems fine to me too today. I guess they must've fixed it.
